"""ajout company_size_raw

Revision ID: 5d3e02ae262f
Revises: 86acd51e7147
Create Date: 2026-09-16 10:53:14.471591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d3e02ae262f'
down_revision: Union[str, Sequence[str], None] = '86acd51e7147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('company_size_raw', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'company_size_raw')
    # ### end Alembic commands ###
