"""ajout colonnes review

Revision ID: 877c14bbc7b2
Revises: 25432423c390
Create Date: 2026-09-15 17:40:45.824474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '877c14bbc7b2'
down_revision: Union[str, Sequence[str], None] = '25432423c390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('review_status', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('reviewed_by', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'reviewed_at')
    op.drop_column('leads', 'reviewed_by')
    op.drop_column('leads', 'review_status')
    # ### end Alembic commands ###
