"""ajout colonnes action (assigned_to, action_message)

Revision ID: d9b32bd0b5ed
Revises: a535a78ea0ff
Create Date: 2026-09-15 12:41:46.602140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9b32bd0b5ed'
down_revision: Union[str, Sequence[str], None] = 'a535a78ea0ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('kb_embeddings_idx_1'), table_name='data_kb_embeddings')
    op.drop_table('data_kb_embeddings')
    op.add_column('leads', sa.Column('assigned_to', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('action_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'action_message')
    op.drop_column('leads', 'assigned_to')
    op.create_table('data_kb_embeddings',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('metadata_', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('node_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('data_kb_embeddings_pkey'))
    )
    op.create_index(op.f('kb_embeddings_idx_1'), 'data_kb_embeddings', [sa.literal_column("(metadata_ ->> 'ref_doc_id'::text)")], unique=False)
    # ### end Alembic commands ###
